### ISSUE TITLE
XML closing tag color different from opening tag color

### ISSUE THREAD

**Issue by npearson72** [reedes/vim-colors-pencil#28]
Is there anyway to make the closing tag have the same color as the closing tag in XML?

Here is what I haveget:

<img width="84" alt="screen shot 2018-12-22 at 8 55 17 pm" src="https://user-images.githubusercontent.com/1323414/50377774-0abd0c00-062c-11e9-9de7-a64d7d41bc54.png">

**Comment by daliusd** [comment]
This is problem in NeoVim. This problem is fixed in Vim. Bug reported for NeoVim.

**Comment by alerque** [comment]
Thanks for tracking that down and reporting @daliusd!

I'm going to close the issue here since it is not actionable in this plugin and indeed will affect all color schemes until fixed. Anyone interested is encouraged to subscript to the NeoVIM issue. Fixing that will make it work for this color scheme as well.
